const GLOBAL_CONSTANT = {
    EXCHANGE : 'COINBASE',
    RECONNECT_INTERVAL: 5000,
    COIN_LIST : ['BTC','ETH','XRP','LTC','BCH','ETC'],
    CURRENCY_LIST : ['USD','GBP','EUR','JPY','ZAR']
};

export default GLOBAL_CONSTANT;